"""
@brief: convert C++ docstring to Python version, first version generated by chat
@date: 27/8/2025
"""

import re

def cpp_comment_to_python_docstring(cpp_comment: str) -> str:
    # 1. 去掉开头和结尾的 /** */
    cpp_comment = cpp_comment.strip()
    cpp_comment = re.sub(r'^/\*\*', '', cpp_comment)
    cpp_comment = re.sub(r'\*/$', '', cpp_comment)

    # 2. 去掉每行开头的 *
    lines = cpp_comment.split('\n')
    cleaned_lines = []
    for line in lines:
        line = re.sub(r'^\s*\* ?', '', line)
        cleaned_lines.append(line)

    # 3. 替换 C++ 风格的标签
    replacements = {
        '@brief:': '@brief:',
        '@link:': '@link:',
        '@author:': '@author:',
        '@date:': '@date:',
        '@Difficulty:': '@Difficulty:',
        '@Label:': '@Label:',
        '@Retrospect': '@Retrospect',
        '@thoughts:': '@thoughts:',
    }

    result_lines = []
    for line in cleaned_lines:
        for k, v in replacements.items():
            if line.startswith(k):
                line = line.replace(k, v)
        result_lines.append(line)

    # 4. 拼成 Python 风格文档字符串
    python_docstring = '"""\n' + '\n'.join(result_lines).strip() + '\n"""'
    return python_docstring


# ==== 测试 ====
cpp_comment = """
/**
 * @brief: Leetcode_162_寻找峰值
 * @link: https://leetcode.cn/problems/find-peak-element/description/
 * @author: liangj.zhang
 * @date: 23/9/2025
 * 
 * @Difficulty: Medium
 * 
 * @Label: Binary Search
 * 
 * @Retrospect(worthy 1 - 5): 3
 * 
 * @thoughts:
 *  + 【思路 1】：二分查找 -- 峰值 -- 红蓝染色
 *      看了灵神的视频：https://www.bilibili.com/video/BV1QK411d76w
 *      峰值这题，竟然也能用二分；
 *      还好这题，只用求任意一个峰顶的下标；
 *      
 *      只求得一个峰顶，左侧染红色，右侧染蓝色，染色，即是告诉自己不用再去考虑的部分；
 *      nums[mid] < nums[mid + 1] => 处于峰顶左侧（，mid 及 mid 左侧染红色，l = mid + 1
 *      else 即 
 *      nums[mid] >= nums[mid + 1] => 处于峰顶，或者峰顶的右侧（，mid 及 mid 右侧染蓝色，r = mid -1
 * 
 *      + 分析：
 *          + 时间复杂度：O(logn)
 *          + 空间复杂度：O(1)
 *      + rank:
 *          + 时间效率：0 ms, 击败 100%
 *          + 空间效率：12.19 MB, 击败 87.95%
 */
"""

print(cpp_comment_to_python_docstring(cpp_comment))
